Added an isData optional parameter to hs.websocket:send()
Hammerspoon/hammerspoon pull request #2765
Opened 2021-03-12 13:07 UTC by latenitefilms

- Closes #2752

2021-03-12 13:09 UTC, latenitefilms commented
@asmagill - Are you able to idiot check this?

@cmsj - I saw your message on the Google Groups, but pod headers we are using look different to the ones you linked to (i.e. there is no `sendString` and `sendData` methods).

2021-03-12 14:32 UTC, asmagill approved these changes
lgtm

2021-03-14 02:19 UTC, cmsj commented
> @cmsj - I saw your message on the Google Groups, but pod headers we are using look different to the ones you linked to (i.e. there is no `sendString` and `sendData` methods).

Ah, looks like that was added in the (now archived) GitHub repo for SocketRocket, but never released.

2021-03-14 02:22 UTC, cmsj requested changes

2021-03-14 02:22 UTC, cmsj commented on extensions/websocket/internal.m
>  /// hs.websocket:send(message) -> object
Needs a [, isData]

2021-03-14 23:03 UTC, cmsj approved these changes

2021-03-14 23:03 UTC, merged