Fixed regression in hs.json which meant it sometimes returned a string instead of a table
Hammerspoon/hammerspoon pull request #2779
Opened 2021-03-15 20:43 UTC by latenitefilms

- Closes #2778

2021-03-15 20:44 UTC, latenitefilms commented
@cmsj - This passes the tests, but do you want to do a quick idiot check to make sure the changes are correct?

2021-03-17 21:14 UTC, cmsj requested changes
One possible improvement, but overall lgtm. Assuming the tests still pass, I'm fine with merging this, although it would be nice to have some json data that would confuse the current version, so we can prove it's fixed.

2021-03-17 21:14 UTC, cmsj commented on extensions/json/internal.m
> +    return [self decode:[json dataUsingEncoding:NSUTF8StringEncoding]];
Maybe here instead of doing `NSString stringWithContentsOfFile` we should just do `NSData dataWithContentsOfFile`?

2021-03-17 21:27 UTC, latenitefilms commented
I'll have a look at this tonight, and see if I can find a scenario that breaks it.

2021-03-19 10:24 UTC, cmsj approved these changes
lgtm

2021-03-19 10:24 UTC, merged