Handle VOX not running in isRunning() - fixes #2906
Hammerspoon/hammerspoon pull request #2908
Opened 2021-06-19 21:55 UTC by von

Fix for case when VOX isn't running and hence hs.application.find("VOX") returns nil. Fixes #2906.

2021-06-20 00:24 UTC, latenitefilms requested changes
I wonder if `hs.application.applicationsForBundleID` should be used instead to reduce the risk of Hammerspoon getting the wrong application (ie if you have a Safari window open with the VOX website, etc)?

2021-06-20 02:11 UTC, von commented
> I wonder if `hs.application.applicationsForBundleID` should be used instead to reduce the risk of Hammerspoon getting the wrong application (ie if you have a Safari window open with the VOX website, etc)?

Makes sense. As I understand `hs.application.applicationsForBundleID` it returns a table with applications with the given BundleID, so the only check that is needed is for a non-empty table. I.e. there is no need to call `isRunning()` on an app from the table to confirm?

2021-06-20 13:31 UTC, von commented
> > I wonder if `hs.application.applicationsForBundleID` should be used instead to reduce the risk of Hammerspoon getting the wrong application (ie if you have a Safari window open with the VOX website, etc)?
> 
> Makes sense. As I understand `hs.application.applicationsForBundleID` it returns a table with applications with the given BundleID, so the only check that is needed is for a non-empty table. I.e. there is no need to call `isRunning()` on an app from the table to confirm?

Change pushed: f8fced0

2021-08-14 22:33 UTC, cmsj commented
Thanks!

2021-08-14 22:33 UTC, merged