Allow the query to still be forwarded when no matching string exists
Hammerspoon/hammerspoon pull request #3232
Opened 2022-06-12 02:36 UTC by halfwit

This is an example of how to implement this, it works in my local testing.
It adds a method, enableDefaultForQuery which can be passed a bool to allow the query to be returned to the final handler, even when it doesn't match an item on the choices list.

2022-07-01 17:23 UTC, cmsj requested changes
I like the look of this, and I also wonder if it might be worth adding the query string to the `choice` dictionary even when a valid choice exists? That doesn't need to be part of this PR, but we should do the `LUA_NOREF`/`LUA_REFNIL` checks before merging.

2022-07-01 17:23 UTC, cmsj commented on extensions/chooser/HSChooser.m
> +    } else if (self.enableDefaultForQuery != NO) {
This should also check that `self.completionCallbackRef` is neither `LUA_NOREF` or `LUA_REFNIL`

2022-07-01 18:55 UTC, halfwit commented
Sorry about the commit/revert, not sure what VSCode was doing there.

2022-11-02 21:47 UTC, merged

2022-11-02 21:47 UTC, cmsj commented
Thanks! Apologies for the slow merging